name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: checkout submodules
        run: |
          git submodule update --init --recursive

      - name: Compile
        run: |
          bash build.bash
          mkdir -p ${{ github.sha }}
          mv *.tar.xz ${{ github.sha }}/
  

